app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('domains/', include('domains.urls')),
    path('', include('accounts.urls')),
]
# path('login/', views.LoginView.as_view(authentication_form=LoginForm), name='login'),

domains/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.DomainListView.as_view(), name='domains'),
    path('search/', views.DomainSearchView.as_view(), name='search'),
    re_path(r'^domain/(?P<pk>\d+)$', views.DomainDetailView.as_view(), name='domain-detail'),
    re_path(r'^domain/(?P<pk>[-\w]+)/ban/$', views.DomainBanView.as_view(), name='domain-ban'),
    re_path(r'^create/$', views.DomainCreate.as_view(), name='domain-create'),
    re_path(r'^create-multiple/$', views.DomainCreateMultiple.as_view(), name='domain-create-multiple'),
    re_path(r'^domain/(?P<pk>[-\w]+)/update/$', views.DomainUpdate.as_view(), name='domain-update'),
    re_path(r'^domain/(?P<pk>[-\w]+)/delete/$', views.DomainDelete.as_view(), name='domain-delete'),
]

domains/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.


class Domain(models.Model):
    name = models.CharField(max_length=50, unique=True)
    STATES = ((1, 'куплен'),
              (2, 'настроен'),
              (3, 'закрыт'),
              (4, 'открыт'),
              (5, 'забанен'))
    state = models.IntegerField(choices=STATES)
    use_date = models.DateField(blank=True, null=True)
    ban_date = models.DateField(blank=True, null=True)

    new_domain = models.OneToOneField(
        'self', on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        permissions = (('ban', 'Ban domain'),)

    def get_absolute_url(self):
        return reverse('domain-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

domains/forms.py
import collections
from django import forms
from .models import Domain
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
import datetime

STATES_WITHOUT_BANNED = ((1, 'куплен'),
                         (2, 'настроен'),
                         (3, 'закрыт'),
                         (4, 'открыт'))


class DateInput(forms.DateInput):
    input_type = 'date'


class DomainCheckForm(forms.ModelForm):
    class Meta:
        model = Domain
        fields = '__all__'

    def clean_name(self):
        name = self.cleaned_data.get('name')
        validate = URLValidator()
        try:
            validate('http://' + name)
        except ValidationError:
            raise ValidationError('Invalid domain name: {}'.format(name))
        domain_exist = Domain.objects.filter(name=name)
        if domain_exist:
            raise ValidationError(
                'domain name must be unique. {} already exist'.format(name))
        return name

    def clean_use_date(self):
        state = self.cleaned_data.get('state')
        use_date = self.cleaned_data['use_date']
        choices = dict(self.fields['state'].choices)
        if state in [1, 2, 3] and use_date:
            raise ValidationError(
                "Can't set use date for domain in state {}".format(choices[state]))
        if state in [4, 5] and not use_date:
            raise ValidationError(
                "You must set use date for domain in state {}".format(choices[state]))
        return use_date

    def clean_ban_date(self):
        state = self.cleaned_data.get('state')
        print(state)
        ban_date = self.cleaned_data.get('ban_date')
        choices = dict(self.fields['state'].choices)
        if state != 5 and ban_date:
            raise ValidationError(
                "Can't set ban date for domain in state {}".format(choices[state]))
        if state == 5 and not ban_date:
            raise ValidationError(
                "You must set ban date for domain in state {}".format(choices[state]))
        return ban_date

    def clean_new_domain(self):
        state = self.cleaned_data.get('state')
        new_domain = self.cleaned_data.get('new_domain')
        choices = dict(self.fields['state'].choices)
        if state in [1, 2, 3, 4] and new_domain:
            raise ValidationError(
                "Can't set new domain for domain in state {}".format(choices[state]))
        if state == 5 and not new_domain:
            raise ValidationError(
                "You must set new domain for domain in state {}".format(choices[state]))
        return new_domain


class DomainCreateMultipleForm(DomainCheckForm):
    domains = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    #state = forms.ChoiceField(choices=STATES_WITHOUT_BANNED, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Domain
        fields = ['domains', 'state', 'use_date']

        widgets = {
            #'domains': forms.Textarea(attrs={'class': 'form-control'}),
            'state': forms.Select(attrs={'class': 'form-control'}),
            'use_date': DateInput(attrs={'class': 'form-control'})
        }

    def clean_domains(self):
        domains = self.cleaned_data.get('domains', '').split()
        validate = URLValidator()
        duplicates = [item for item, count in collections.Counter(
            domains).items() if count > 1]
        if duplicates:
            raise ValidationError(
                'domain name must be unique. {} duplicated'.format(' '.join(duplicates)))
        for d in domains:
            try:
                validate('http://' + d)
            except ValidationError:
                raise ValidationError('Invalid domain name: {}'.format(d))
            domain_exist = Domain.objects.filter(name=d)
            if domain_exist:
                raise ValidationError(
                    'domain name must be unique. {} already exist'.format(d))
        return domains


class DomainCreateForm(DomainCheckForm):
    class Meta:
        model = Domain
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.Select(attrs={'class': 'form-control'}),
            'use_date': DateInput(attrs={'class': 'form-control'}),
            'ban_date': DateInput(attrs={'class': 'form-control'}),
            'new_domain': forms.Select(attrs={'class': 'form-control'})
        }


class DomainChangeForm(DomainCheckForm):
    class Meta:
        model = Domain
        exclude = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.Select(attrs={'class': 'form-control'}),
            'use_date': DateInput(attrs={'class': 'form-control'}),
            'ban_date': DateInput(attrs={'class': 'form-control'}),
            'new_domain': forms.Select(attrs={'class': 'form-control'})
        }


class DomainBanForm(DomainChangeForm):
    class Meta:
        model = Domain
        fields = ('state', 'ban_date', 'new_domain')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.Select(attrs={'class': 'form-control', 'disabled': True}),
            'use_date': DateInput(attrs={'class': 'form-control'}),
            'ban_date': DateInput(attrs={'class': 'form-control'}),
            'new_domain': forms.Select(attrs={'class': 'form-control'})
        }

domains/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, reverse
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views import generic, View
from .models import Domain
from django.core.paginator import Paginator
from .forms import DomainBanForm, DomainCreateMultipleForm, DomainCheckForm, DomainCreateForm, DomainChangeForm
import datetime


def domains_ready_exclude_pk(pk):
    return Domain.objects.filter(state__in=[2, 3]).exclude(pk=pk)


class DomainListView(PermissionRequiredMixin, View):
    permission_required = ('domains.can_change_domain')

    def get(self, request):
        query = self.request.GET.get('q')
        if query:
            domains = Domain.objects.filter(
                name__contains=query).order_by('name')
        else:
            domains = Domain.objects.all().order_by('name')
        paginator = Paginator(domains, 15)
        page = request.GET.get('page')
        dom = paginator.get_page(page)
        return render(request, 'domains/domain_list.html', {'domain_list': dom})


class DomainDetailView(LoginRequiredMixin, generic.DetailView):
    model = Domain


class DomainBanView(PermissionRequiredMixin, View):
    permission_required = ('domains.ban')

    def get(self, request, pk):
        domain = get_object_or_404(Domain, pk=pk)
        form = DomainBanForm(initial={'state': 5,
                                      'ban_date': datetime.date.today()})
        form.fields['new_domain'].queryset = domains_ready_exclude_pk(pk)
        return render(request, 'domains/domain_ban.html', {'form': form, 'domain': domain})

    def post(self, request, pk):
        domain = get_object_or_404(Domain, pk=pk)
        data = request.POST.copy()
        data['state'] = 5
        form = DomainBanForm(data)

        if form.is_valid():
            domain.state = form.cleaned_data['state']
            domain.ban_date = form.cleaned_data['ban_date']
            domain.new_domain = form.cleaned_data['new_domain']

            domain.new_domain.use_date = datetime.date.today()
            domain.new_domain.state = 4
            domain.new_domain.save()

            domain.save()
            print(domain, domain.ban_date)
            return HttpResponseRedirect(reverse('index'))
        return render(request, 'domains/domain_ban.html', {'form': form, 'domain': domain})


class DomainCreate(LoginRequiredMixin, View):
    def get(self, request):
        form = DomainCreateForm()
        return render(request, 'domains/domain_form.html', {'form': form})

    def post(self, request):
        form = DomainCreateForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            state = form.cleaned_data.get('state')
            use_date = form.cleaned_data.get('use_date')
            ban_date = form.cleaned_data.get('ban_date')
            new_domain = form.cleaned_data.get('new_domain')

            Domain.objects.create(name=name,
                                  state=state,
                                  use_date=use_date,
                                  ban_date=ban_date,
                                  new_domain=new_domain)
            return HttpResponseRedirect(reverse('domains'))
        return render(request, 'domains/domain_form.html', {'form': form})


class DomainUpdate(LoginRequiredMixin, View):
    def get(self, request, pk):
        domain = get_object_or_404(Domain, pk=pk)
        form = DomainChangeForm(instance=domain)
        return render(request, 'domains/domain_form.html', {'form': form, 'domain': domain})

    def post(self, request, pk):
        form = DomainChangeForm(request.POST)
        if form.is_valid():
            domain = get_object_or_404(Domain, pk=pk)
            domain.state = form.cleaned_data.get('state')
            domain.use_date = form.cleaned_data.get('use_date')
            domain.ban_date = form.cleaned_data.get('ban_date')
            domain.new_domain = form.cleaned_data.get('new_domain')
            domain.save()
            return HttpResponseRedirect(reverse('domains'))
        return render(request, 'domains/domain_form.html', {'form': form})


class DomainDelete(LoginRequiredMixin, generic.DeleteView):
    model = Domain
    success_url = reverse_lazy('domains')


class DomainCreateMultiple(LoginRequiredMixin, View):
    def get(self, request):
        form = DomainCreateMultipleForm()
        return render(request, 'domains/domain_form.html', {'form': form})

    def post(self, request):
        form = DomainCreateMultipleForm(request.POST)

        if form.is_valid():
            new_domains = []
            names = form.cleaned_data['domains']
            use_date = form.cleaned_data['use_date']
            state = form.cleaned_data['state']
            for name in names:
                new_domains.append(
                    Domain(name=name, state=state, use_date=use_date))
            Domain.objects.bulk_create(new_domains)

            return HttpResponseRedirect(reverse('domains'))
        return render(request, 'domains/domain_form.html', {'form': form})


class DomainSearchView(LoginRequiredMixin, View):
    def get(self, request):
        query = self.request.GET.get('q')
        context = {}
        if query:
            try:
                domain = Domain.objects.get(name=query)
                return HttpResponseRedirect(domain.get_absolute_url())
            except Domain.DoesNotExist:
                context = {'error': '{} not found'.format(query)}
        print(context)
        return render(request, 'search.html', context)

domains/templates/domains/domain_ban.html
{% extends "base_generic.html" %}


{% block content %}
<div class="row " style="height: 40rem;">
    <div class="col"></div>
    <div class="col-6 align-self-center">
        <form action="" method="post">
            {% csrf_token %}
            {% if form.errors %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{error}}
            </div>
            {% endfor %}
            {% endif %}
            <div class="card">
                <h5 class="card-header">{{domain.name}}</h5>
                <div class="card-body">
                    <table class="table table-borderless">
                        <tbody>
                            {% for field in form %}
                            <tr>
                                {% if field.errors %}
                                {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error }}
                                </div>
                                {% endfor %}
                                {% endif %}
                                <td>{{ field.label }}</td>
                                <td>{{ field }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-body">
                    <div class="float-right">
                        <input type="submit" class="btn btn-outline-danger" value="Ban" />
                        <input action="action" class="btn btn-outline-success" onclick="location.href='{{ domain.get_absolute_url }}'" value="Cancel" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

domains/templates/domains/domain_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}




<div class="row " style="height: 50rem;">
    <div class="col"></div>
    <div class="col-6 align-self-center">
        <h2>Delete domain</h2>

        <p>Are you sure you want to delete the domain: {{ domain }}?</p>

        <form action="" method="POST">
          {% csrf_token %}
          <input type="submit" class="btn btn-outline-danger" action="" value="Delete" />
          <input action="action" class="btn btn-outline-success" onclick="location.href='{{ domain.get_absolute_url }}'" value="Cancel" />
        </form>
    </div>
    <div class="col"></div>
  </div>




{% endblock %}

domains/templates/domains/domain_detail.html
{% extends "base_generic.html" %}


{% block content %}
<div class="row " style="height: 40rem;">
  <div class="col"></div>
  <div class="col-8 align-self-center">
    <div class="card" style="width: 36rem;">
      <h5 class="card-header">{{domain.name}}</h5>
      <div class="card-body">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td>State</td>
              <td>{{ domain.get_state_display }}</td>
            </tr>
            <tr>
              <td>Use date</td>
              <td>{{ domain.use_date }}</td>
            </tr>
            <tr>
              <td>Ban date</td>
              <td>{{ domain.ban_date }}</td>
            </tr>
            <tr>
              <td>replaced by</td>
              <td>{{ domain.new_domain }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="card-body">
        <div class="float-right">
          {% if domain.state == 5 %}
          <a class="btn btn-outline-danger disabled" href="{% url 'domain-ban' domain.id %}" role="button">Ban</a>
          {% elif perms.domains.ban %}
          <a class="btn btn-outline-danger" href="{% url 'domain-ban' domain.id %}" role="button">Ban</a>
          {% endif %}
          {% if perms.domains.can_change_domain %}
          <a class="btn btn-outline-primary" href="{% url 'domain-update' domain.id %}" role="button">Change</a>
          {% endif %}
          {% if perms.domains.can_delete_domain %}
          <a class="btn btn-outline-danger" href="{% url 'domain-delete' domain.id %}?next={{ request.path|urlencode }}"
            role="button">Delete</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="col"></div>
</div>
{% endblock %}

domains/templates/domains/domain_form.html
{% extends "base_generic.html" %}
{% block content %}
<div class="row " style="height: 40rem;">
    <div class="col"></div>
    <div class="col-8 align-self-center">
        <form action="" method="post">
            {% csrf_token %}
            {% if form.errors %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-warning">
                {{error}}
            </div>
            {% endfor %}
            {% endif %}
            <div class="card" style="width: 36rem;">
                <h5 class="card-header">{% if domain %}{{domain.name}}{% else %}New domain(s){% endif %}</h5>
                <div class="card-body">
                    <table class="table table-borderless">
                        <tbody>
                            {% for field in form %}
                            <tr>
                                {% if field.errors %}
                                {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error }}
                                </div>
                                {% endfor %}
                                {% endif %}
                                <td>{{ field.label }}</td>
                                <td>{{ field }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-body">
                    <div class="float-right">
                        <input type="submit" class="btn btn-outline-primary" value="Ok" />
                        <input action="action" class="btn btn-outline-success" onclick=
                        {% if domain %}"location.href='{{ domain.get_absolute_url }}'"
                        {% else  %}"location.href='{% url 'domains' %}'"
                        {% endif %}
                            type="button" value="Cancel" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

domains/templates/domains/domain_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row py-5">
  <div class="col">
    <h4>Domains list</h4>
  </div>
  <div class="col-4 float-right">
    <form class="form-inline" method="GET" action="">
      <div class="form-group mx-sm-3 mb-2">
        <label for="domain-search" class="sr-only">Search domain</label>
        <input type="text" class="form-control" id="domain-search" name="q" placeholder="">
      </div>
      <button type="submit" class="btn btn-success mb-2">Search</button>
    </form>
  </div>
</div>
<div class="row" style="min-height: 36rem;">
  <div class="col">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">State</th>
          <th scope="col">Used</th>
          <th scope="col">Banned</th>
          <th scope="col">Replaced by</th>
        </tr>
      </thead>
      <tbody>
        {% for domain in domain_list %}
        <tr>
          <td><a href="{{ domain.get_absolute_url }}">{{ domain.name }}</a></td>
          <td>{{ domain.get_state_display }}</td>
          <td>{{ domain.use_date }}</td>
          <td>{{ domain.ban_date }}</td>
          <td>
            {% if domain.new_domain %}
            <a href="{{ domain.new_domain.get_absolute_url }}">{{ domain.new_domain }}</a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<div class="row align-items-center">
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
      {% if domain_list.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">First</span>
        </a>
      </li>
      <li class="page-item"><a class="page-link" href="?page={{ domain_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">First</span>
        </a>
      </li>
      <li class="page-item disabled"><a class="page-link" href="">Previous</a></li>
      {% endif %}
      {% for page in domain_list.paginator.page_range %}
      {% if page == domain_list.number %}
      <li class="page-item active"><a class="page-link" href="?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ page }}</a></li>
      {%  else %}
      <li class="page-item"><a class="page-link" href="?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ page }}</a></li>
      {% endif %}
      {% endfor %}
      {% if domain_list.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ domain_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ domain_list.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Last</span>
        </a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="">Next</a>
      </li>
      <li class="page-item disabled">
        <a class="page-link" href="" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Last</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>
</div>
{% endblock %}

domains/templates/domains/domain_multiple_form.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Domain: {{domain.name}}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}